
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/antoninjean/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/232.9921.42/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Darwin - 22.5.0 - arm64
...
