sources/src/api/noise/Noise.cpp File Reference
#include <api/noise/Noise.h>
#include <utility>
Functions
void _heatMap (int value, int max, int &red, int &green, int &blue)
void _interpolateColor (int value, int max, float midThreshold, int minR, int minG, int minB, int maxR, int maxG, int maxB, int &R, int &G, int &B)
void _groupColor (int value, int max, int amountOfGroup, int minR, int minG, int minB, int maxR, int maxG, int maxB, int &R, int &G, int &B)
void oceanColor (int value, int max, int &red, int &green, int &blue)
void beachColor (int value, int max, int &red, int &green, int &blue)
void plainColor (int value, int max, int &red, int &green, int &blue)
void mountainColor (int value, int max, int &red, int &green, int &blue)
void snowColor (int value, int max, int &red, int &green, int &blue)
void _terrainTexture (int value, int max, int &red, int &green, int &blue)
void _saveterrainTexture (int value, int max, int &red, int &green, int &blue)
Function Documentation
_groupColor()
void _groupColor (int value, int max, int amountOfGroup, int minR, int minG, int minB, int maxR, int maxG, int maxB, int & R, int & G, int & B)
Definition at line 121 of file Noise.cpp.
                                                                                                                                            {
    // Calculer la taille de chaque groupe
    int groupSize = max / amountOfGroup;
    // Déterminer le groupe auquel appartient la valeur
    int groupIndex = value / groupSize;
    // Interpoler la couleur en fonction du groupe
    _interpolateColor(groupIndex, amountOfGroup - 1, 0.5, minR, minG, minB, maxR, maxG, maxB, R, G, B);
}
References _interpolateColor().
Referenced by plainColor().
_heatMap()
void _heatMap (int value, int max, int & red, int & green, int & blue)
Definition at line 99 of file Noise.cpp.
                                                                   {
    int max_2 = max / 3;
    int max_3 = max_2 * 2;
    red = std::min(max, value * 3);
    green = std::min(max, std::max(0, (value - max_2) * 3));
    blue = std::min(max, std::max(0, (value - max_3) * 3));
}
Referenced by Noise::toPPM().
_interpolateColor()
void _interpolateColor (int value, int max, float midThreshold, int minR, int minG, int minB, int maxR, int maxG, int maxB, int & R, int & G, int & B)
Definition at line 107 of file Noise.cpp.
                                                                                                                                                   {
    // Calculer le facteur d'interpolation
    double factor = static_cast<double>(value) / max;
    if (factor < midThreshold) {
        factor = factor * (1. - midThreshold);
    } else {
        factor = (factor - midThreshold) / (1. - midThreshold);
    }
    // Interpoler chaque composante de couleur
    R = minR + static_cast<int>(factor * (maxR - minR));
    G = minG + static_cast<int>(factor * (maxG - minG));
    B = minB + static_cast<int>(factor * (maxB - minB));
}
Referenced by _groupColor(), beachColor(), mountainColor(), oceanColor(), and snowColor().
_saveterrainTexture()
void _saveterrainTexture (int value, int max, int & red, int & green, int & blue)
Definition at line 172 of file Noise.cpp.
                                                                              {
    int step = max / 16;
    int sea_level = step*4;
    int beach_level = step * 6;
    int plain_level = step * 12;
    int mountain_level = max * 15;
    if (value < sea_level) {
        blue = 255;
        green = std::min(max, value * 5 / sea_level);
        red = 0;
    } else if (value < beach_level) {
        blue = 0;
        green = std::min(max, (value - sea_level) * 10 / (beach_level - sea_level));
        red = std::min(max, (value - sea_level) * 10 / (beach_level - sea_level));
    } else if (value < plain_level) {
        blue = 0;
        green = std::min(max, (value - beach_level) * 3 / (plain_level - beach_level));
        red = 0;
    } else if (value < mountain_level) {
        blue = green = red = std::min(max, (value - plain_level) * 3 / (plain_level - mountain_level));
    } else {
        blue = red = green = max;
    }
}
_terrainTexture()
void _terrainTexture (int value, int max, int & red, int & green, int & blue)
Definition at line 151 of file Noise.cpp.
                                                                          {
    int step = max / 32;
    int quota = value / step;
    if (quota < 4) { // DEEP OCEAN LEVEL
        red = 8;
        green = 23;
        blue = 116;
    } else if (quota < 9) { // SHORES LEVEL
        oceanColor(value, step * 9, red, green, blue);
    } else if (quota < 11) { // BEACH LEVEL
        beachColor(value, step * 11, red, green, blue);
    } else if (quota < 28) { // PLAIN LEVEL
        plainColor(value, step * 28, red, green, blue);
    } else if (quota < 32) { // MOUNTAIN LEVEL
        mountainColor(value, step * 32, red, green, blue);
    } else { // SNOW LEVEL
        snowColor(value, step * 32, red, green, blue);
    }
}
References beachColor(), mountainColor(), oceanColor(), plainColor(), and snowColor().
Referenced by Noise::toPPM().
beachColor()
void beachColor (int value, int max, int & red, int & green, int & blue)
Definition at line 136 of file Noise.cpp.
                                                                     {
    _interpolateColor(value, max, 0.8, 99, 94, 72, 224, 214, 169, red, green, blue);
}
References _interpolateColor().
Referenced by _terrainTexture().
mountainColor()
void mountainColor (int value, int max, int & red, int & green, int & blue)
Definition at line 144 of file Noise.cpp.
                                                                        {
    _interpolateColor(value, max, 0.6, 35, 35, 35, 159, 198, 198, red, green, blue);
}
References _interpolateColor().
Referenced by _terrainTexture().
oceanColor()
void oceanColor (int value, int max, int & red, int & green, int & blue)
Definition at line 132 of file Noise.cpp.
                                                                     {
    _interpolateColor(value, max, 0.8, 8, 23, 116, 119, 167, 179, red, green, blue);
}
References _interpolateColor().
Referenced by _terrainTexture().
plainColor()
void plainColor (int value, int max, int & red, int & green, int & blue)
Definition at line 140 of file Noise.cpp.
                                                                     {
    _groupColor(value, max, 16, 141, 199, 97, 48, 86, 30, red, green, blue);
}
References _groupColor().
Referenced by _terrainTexture().
snowColor()
void snowColor (int value, int max, int & red, int & green, int & blue)
Definition at line 148 of file Noise.cpp.
                                                                    {
    _interpolateColor(value, max, 0.8, 159, 198, 198, 255, 255, 255, red, green, blue);
}
References _interpolateColor().
Referenced by _terrainTexture().