BitMap< T > Class Template Reference
#include <BitMap.h>
Public Member Functions
BitMap (size_t width, size_t height, T defaultValue)
BitMap (size_t width, size_t height, std::vector< std::vector< T > > values)
unsigned int getHeight ()
unsigned int getWidth ()
unsigned int getSize ()
const T get (const size_t col, const size_t line) const
T put (const size_t &col, const size_t &line, T value)
Friends
template<typename U >
bool operator== (const BitMap< U > &self, const BitMap< U > &other)
template<typename U >
bool operator!= (const BitMap< U > &self, const BitMap< U > &other)
template<typename U >
BitMap< T > operator+ (const BitMap< U > &self, T scalar)
template<typename U >
BitMap< T > operator+ (BitMap< U > self, BitMap< U > other)
Detailed Description
template<typename T>
class BitMap< T >
Definition at line 13 of file BitMap.h.
Constructor & Destructor Documentation
BitMap() [1/2]
template<typename T >
BitMap< T >::BitMap (size_t width, size_t height, T defaultValue) [inline], [explicit]
Definition at line 15 of file BitMap.h.
                                                                 : m_width(width), m_height(height), m_data(std::vector<std::vector<T> >(height))
    {
        for (int i = 0; i < m_height; i++) {
            m_data[i] = std::vector<T>(width, defaultValue);
        }
    }
BitMap() [2/2]
template<typename T >
BitMap< T >::BitMap (size_t width, size_t height, std::vector< std::vector< T > > values) [inline]
Definition at line 22 of file BitMap.h.
    : m_width {width}
    , m_height {height}
    , m_data {values}
    {}
Member Function Documentation
get()
template<typename T >
const T BitMap< T >::get (const size_t col, const size_t line) const [inline]
Definition at line 51 of file BitMap.h.
                                                           {
        if (col >= m_width || line >= m_height) {
            throw std::invalid_argument("Invalid index (" + std::to_string(col) + ", " + std::to_string(line) +
                "), in Bitmap of size (" + std::to_string(m_width) + ", " + std::to_string(m_height) + ").");
        }
        return m_data[line][col];
    }
Referenced by Terrain::getTerrain(), BitMap< T >::put(), Worley_noise::test(), Noise::toPGM(), and Noise::toPPM().
getHeight()
template<typename T >
unsigned int BitMap< T >::getHeight () [inline]
Definition at line 28 of file BitMap.h.
                             {
        return m_height;
    }
Referenced by Worley_noise::test().
getSize()
template<typename T >
unsigned int BitMap< T >::getSize () [inline]
Definition at line 36 of file BitMap.h.
                           {
        return m_height * m_width;
    }
getWidth()
template<typename T >
unsigned int BitMap< T >::getWidth () [inline]
Definition at line 32 of file BitMap.h.
                            {
        return m_width;
    }
Referenced by Worley_noise::test().
put()
template<typename T >
T BitMap< T >::put (const size_t & col, const size_t & line, T value) [inline]
Definition at line 59 of file BitMap.h.
                                                          {
        if (col >= m_width || line >= m_height) {
            throw std::invalid_argument("Invalid index (" + std::to_string(col) + ", " + std::to_string(line) +
                "), in Bitmap of size (" + std::to_string(m_width) + ", " + std::to_string(m_height) + ").");
        }
        T oldValue = get(col, line);
        m_data[line][col] = value;
        return oldValue;
    }
References BitMap< T >::get().
Referenced by ValueNoise::genNoise(), and Terrain::getTerrain().
Friends And Related Symbol Documentation
operator!=
template<typename T >
template<typename U >
bool operator!= (const BitMap< U > & self, const BitMap< U > & other) [friend]
operator+ [1/2]
template<typename T >
template<typename U >
BitMap< T > operator+ (BitMap< U > self, BitMap< U > other) [friend]
operator+ [2/2]
template<typename T >
template<typename U >
BitMap< T > operator+ (const BitMap< U > & self, T scalar) [friend]
operator==
template<typename T >
template<typename U >
bool operator== (const BitMap< U > & self, const BitMap< U > & other) [friend]
The documentation for this class was generated from the following file:
sources/inc/api/noise/BitMap.h