Environment Class Reference
#include <Environment.h>
Public Member Functions
Environment (std::string name, Terrain heightTerrain, Terrain biomeTerrain)
Terrain getHeightTerrain () const
Terrain getBiomeTerrain () const
std::string getName () const
Environment (std::string name, Terrain heightTerrain, Terrain biomeTerrain)
Terrain getHeightTerrain () const
Terrain getBiomeTerrain () const
std::string getName () const
void toPEM (const char *filename, int maxHeight=0) const
Static Public Member Functions
static Environment newEnvironment (std::string name, Terrain heightTerrain)
static Environment newEnvironment (std::string name, Terrain heightTerrain)
Detailed Description
Definition at line 8 of file Environment.h.
Constructor & Destructor Documentation
Environment() [1/2]
Environment::Environment (std::string name, Terrain heightTerrain, Terrain biomeTerrain) [inline]
Definition at line 14 of file Environment.h.
                                                                            :
        name(name),
        heightTerrain(heightTerrain),
        biomeTerrain(biomeTerrain) {};
Environment() [2/2]
Environment::Environment (std::string name, Terrain heightTerrain, Terrain biomeTerrain) [inline]
Definition at line 14 of file Environment.hpp.
                                                                            :
        name(name),
        m_heightTerrain(heightTerrain),
        m_biomeTerrain(biomeTerrain) {};
Member Function Documentation
getBiomeTerrain() [1/2]
Terrain Environment::getBiomeTerrain () const [inline]
Definition at line 23 of file Environment.h.
                                    {
        return biomeTerrain;
    }
getBiomeTerrain() [2/2]
Terrain Environment::getBiomeTerrain () const [inline]
Definition at line 23 of file Environment.hpp.
                                    {
        return m_biomeTerrain;
    }
getHeightTerrain() [1/2]
Terrain Environment::getHeightTerrain () const [inline]
Definition at line 19 of file Environment.h.
                                     {
        return heightTerrain;
    }
getHeightTerrain() [2/2]
Terrain Environment::getHeightTerrain () const [inline]
Definition at line 19 of file Environment.hpp.
                                     {
        return m_heightTerrain;
    }
getName() [1/2]
std::string Environment::getName () const [inline]
Definition at line 27 of file Environment.h.
                              {
        return name;
    }
getName() [2/2]
std::string Environment::getName () const [inline]
Definition at line 27 of file Environment.hpp.
                              {
        return name;
    }
newEnvironment() [1/2]
static Environment Environment::newEnvironment (std::string name, Terrain heightTerrain) [inline], [static]
Definition at line 31 of file Environment.h.
                                                                             {
        return Environment(name, heightTerrain, Terrain(name + "_biome", heightTerrain.getSeed()));
    }
References Terrain::getSeed().
Referenced by DefaultGenerator::getEnvironment().
newEnvironment() [2/2]
static Environment Environment::newEnvironment (std::string name, Terrain heightTerrain) [inline], [static]
Definition at line 31 of file Environment.hpp.
                                                                             {
        return Environment(name, heightTerrain, Terrain(name + "_biome", heightTerrain.getSeed()));
    }
References Terrain::getSeed().
toPEM()
void Environment::toPEM (const char * filename, int maxHeight = 0) const
Definition at line 7 of file Environment.cpp.
{}
The documentation for this class was generated from the following files:
sources/inc/api/Terrain/Environment.h
sources/inc/api/Terrain/Environment.hpp
sources/src/api/Terrain/Environment.cpp