Noise Class Reference
#include <Noise.h>
Public Member Functions
Noise (BitMap< int > bitmap, const size_t seed, const size_t width, const size_t height, const size_t frequency)
Noise Object, describing its content, with parameters such as.
const BitMap< int > & getBitmap () const
size_t getSeed () const
size_t getWidth () const
size_t getHeight () const
size_t getFrequency () const
void toPGM (const char *filename, int max=0) const
Generate a PGM file using the values contained in the noise.
void toPPM (const char *filename, void(*colorFunction)(int, int, int &, int &, int &), int max=0) const
void toPPM (const char *filename, ENoiseColorFunction function, int max=0) const
Detailed Description
Definition at line 16 of file Noise.h.
Constructor & Destructor Documentation
Noise()
Noise::Noise (BitMap< int > bitmap, const size_t seed, const size_t width, const size_t height, const size_t frequency)
Noise Object, describing its content, with parameters such as.
Parameters
bitmap The content of the noise described as a bitmap
seed the seed used to generate the noise
width the width of the windowed bitmap created
height the height of the windowed bitmap created
frequency the frequency used to create the noise
Definition at line 9 of file Noise.cpp.
        : m_bitmap(std::move(bitmap)), m_seed(seed), m_width(width), m_height(height), m_frequency(frequency) {}
Member Function Documentation
getBitmap()
const BitMap< int > & Noise::getBitmap () const
Definition at line 13 of file Noise.cpp.
                                          {
    return m_bitmap;
}
getFrequency()
size_t Noise::getFrequency () const
Definition at line 29 of file Noise.cpp.
                                 {
    return m_frequency;
}
getHeight()
size_t Noise::getHeight () const
Definition at line 25 of file Noise.cpp.
                              {
    return m_height;
}
getSeed()
size_t Noise::getSeed () const
Definition at line 17 of file Noise.cpp.
                            {
    return m_seed;
}
getWidth()
size_t Noise::getWidth () const
Definition at line 21 of file Noise.cpp.
                             {
    return m_width;
}
toPGM()
void Noise::toPGM (const char * filename, int max = 0) const
Generate a PGM file using the values contained in the noise.
Parameters
filename A string describing the name of the PGM file
Definition at line 37 of file Noise.cpp.
                                                     {
    // Looking for the maximum value in the noise
    for (size_t x = 0; x < m_width; x++){
        for (size_t y = 0; y < m_height; y++){
            if (max < m_bitmap.get(x, y)){
                max = m_bitmap.get(x, y);
            }
        }
    }
    FILE * image;
    unsigned char* format;
    image = fopen(filename, "wb");
    fprintf(image, "P2\n");
    fprintf(image, "%lu %lu\n", m_width, m_height);
    fprintf(image, "%d\n", max);
    
    for (size_t x = 0; x < m_width; x++){
        for (size_t y = 0; y < m_height; y++){
            int pixel_val = m_bitmap.get(x, y); // Value of the pixel at coordinates (x, y)
            fprintf(image,"%d ", pixel_val < 0 ? 0 : pixel_val);
        }
        fprintf(image, "\n");
    }
    fclose(image);
}
References BitMap< T >::get().
toPPM() [1/2]
void Noise::toPPM (const char * filename, ENoiseColorFunction function, int max = 0) const
Definition at line 227 of file Noise.cpp.
                                                                                   {
    switch (function) {
        case HEATMAP: toPPM(filename, &_heatMap, max); break;
        case TERRAIN: toPPM(filename, &_terrainTexture, max); break;
    }
}
References _heatMap(), _terrainTexture(), HEATMAP, TERRAIN, and toPPM().
toPPM() [2/2]
void Noise::toPPM (const char * filename, void(*)(int, int, int &, int &, int &) colorFunction, int max = 0) const
Definition at line 198 of file Noise.cpp.
                                                                                                         {
 // Looking for the maximum value in the noise
    for (size_t x = 0; x < m_width; x++){
        for (size_t y = 0; y < m_height; y++){
            if (max < m_bitmap.get(x, y)){
                max = m_bitmap.get(x, y);
            }
        }
    }
    FILE * image;
    unsigned char* format;
    image = fopen(filename, "wb");
    fprintf(image, "P3\n");
    fprintf(image, "%lu %lu\n", m_width, m_height);
    fprintf(image, "%d\n", max);
    int red, blue, green;
    for (size_t x = 0; x < m_width; x++){
        for (size_t y = 0; y < m_height; y++){
            int value = m_bitmap.get(x, y);
            colorFunction(value, max, red, green, blue);
            fprintf(image,"%d %d %d ", red, green, blue);
        }
        fprintf(image, "\n");
    }
    fclose(image);
}
References BitMap< T >::get().
Referenced by toPPM().
The documentation for this class was generated from the following files:
sources/inc/api/noise/Noise.h
sources/src/api/noise/Noise.cpp